/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACarousel: typeof import('ant-design-vue/es')['Carousel']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    Agreement: typeof import('./../../shared/components/Agreement/index.vue')['default']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputGroup: typeof import('ant-design-vue/es')['InputGroup']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    AModal: typeof import('ant-design-vue/es')['Modal']
    AProgress: typeof import('ant-design-vue/es')['Progress']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    AUpload: typeof import('ant-design-vue/es')['Upload']
    BgBox: typeof import('./../../shared/components/BgBox/index.vue')['default']
    DatePicker: typeof import('./../../shared/components/date-picker/index.vue')['default']
    Image: typeof import('./../../shared/components/Image/index.vue')['default']
    JAlert: typeof import('./../../shared/components/PAGES/JAlert.vue')['default']
    NavBar: typeof import('./../../shared/components/NavBar/index.vue')['default']
    Protocol: typeof import('./../../shared/components/Protocol/index.vue')['default']
    ResultDialog: typeof import('./../../shared/components/PAGES/ResultDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./../../shared/components/date-picker/select.vue')['default']
    SmartForm: typeof import('./../../shared/components/SmartForm/index.vue')['default']
    SvgImage: typeof import('./../../shared/components/SvgImage/index.vue')['default']
    WeChatCode: typeof import('./../../shared/components/WeChatCode/index.vue')['default']
  }
}
