/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    ConfirmDialog: typeof import('./components/confirmDialog/index.vue')['default']
    DatePicker: typeof import('./components/datePicker/index.vue')['default']
    ErrorText: typeof import('./components/errorText/index.vue')['default']
    Input: typeof import('./components/input/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./components/datePicker/select.vue')['default']
  }
}
